//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMLightMessengerDemo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOption
    {
        public ProductOption()
        {
            this.OrderItemOptions = new HashSet<OrderItemOption>();
        }
    
        public int Id { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string Factor { get; set; }
        public string IsFizzaOption { get; set; }
        public string IsSaladOption { get; set; }
    
        public virtual ICollection<OrderItemOption> OrderItemOptions { get; set; }
    }
}
